### ISSUE TITLE
Custom password hash fails to start MQ properly

### ISSUE THREAD

**Issue by blankdots** [EGA-archive/LocalEGA-mq#2]
### Expected Behavior
When running with `docker run -e MQ_PASSWORD_HASH=<custom_pass_hash> -e CEGA_CONNECTION=amqp://legatest:legatest@cega-mq:5672/lega -e MQ_USER=guest egarchive/lega-mq` image starts properly.

### Current Behavior
When trying to start the image with  a custom password hash the RabbitMQ loading stops with:
```
Waiting for rabbit@f7e6abcb0771
pid is 1
+ (( ROUND<0 ))
+ ROUND=30
+ rabbitmqadmin import /etc/rabbitmq/defs-cega.json

=WARNING REPORT==== 23-Mar-2019::04:21:33 ===
HTTP access denied: user 'guest' - invalid credentials
*** Access refused: /api/definitions

+ (( ROUND<0 ))
+ sleep 1
+ 30
/usr/local/bin/entrypoint.sh: line 131: 30: command not found
```
when running with `guest` password hash:
`docker run -e MQ_PASSWORD_HASH=4tHURqDiZzypw0NTvoHhpn8/MMgONWonWxgRZ4NXgR8nZRBz -e CEGA_CONNECTION=amqp://legatest:legatest@cega-mq:5672/lega -e MQ_USER=guest egarchive/lega-mq` MQ starts ok.

### Possible Solution
Load the configuration files externally seems to help like in this repo: https://github.com/uio-bmi/localega-broker or In the helm charts repository.

### Steps to Reproduce
1. generate password hash using `https://github.com/EGA-archive/LocalEGA/blob/master/extras/rabbitmq_pwhash.py`
2. build image
3. run with `docker run -e MQ_PASSWORD_HASH=<custom_pass_hash> -e CEGA_CONNECTION=amqp://legatest:legatest@cega-mq:5672/lega -e MQ_USER=guest egarchive/lega-mq`

### Context (Environment)
Trying to add custom password to: https://github.com/EGA-archive/LocalEGA/pull/44

**Comment by silverdaz** [comment]
`rabbitmqadmin import /etc/rabbitmq/defs-cega.json` needs to be run with the user's credentials (that latter has admin rights).
