### ISSUE TITLE
Reuse parent image's entrypoint

### ISSUE THREAD

**Issue by dtitov** [EGA-archive/LocalEGA-mq#8]
### Description
I think that we shouldn't ignore entrypoints of base images if we are inheriting them, specifically in the case with RabbitMQ. Currently, we are basically overriding parent entrypoint, but what we should really do is extending it. The reason for this is that parent entrypoint may contain some important commands that we will not get in our image if we override it. For example, currently in the base entrypoint we have:
1. `# allow the container to be started with --user`
2. `# if long and short hostnames are not the same, use long hostnames`
3. `# http://stackoverflow.com/a/2705678/433558`
4. Etc.

This is a bunch of work-arounds and tweaks, applied in the base entrypoint. I'm not saying that we need all of them at the moment (or even any of them), but it might be the case that when we update RabbitMQ to the newer version, they may include some other fixes there, which we simply won't get.

### Proposed solution
`exec /usr/local/bin/docker-entrypoint.sh "$@"`

instead of

`exec "$@"`

in the `entrypoint.sh`

### Definition of Done
Parent entrypoint is called in our entrypoint.

**Comment by silverdaz** [comment]
Closing this issue, as you can inject your own entrypoint when you instanciate the container
